- name: Download | CheckMK CentOS 6
  become: yes
  get_url:
    url: "{{ centos_agent_package }}"
    validate_certs: False
    dest: /root/
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Install | CheckMK CentOS 6
  become: yes
  yum:
    name: /root/check-mk-agent-1.5.0p22-1.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_version =="6"

- name: Install | CheckMK Ubuntu 14
  become: yes
  apt:
    deb: "{{ debian_agent_package }}"
    state: present
    validate_certs: False
    update_cache: yes
  when: ansible_os_family == "Debian" and ansible_distribution_version == "14"
  
- name: Install xinetd | CentOS
  become: yes
  yum:
    name: xinetd
    state: present
  when: ansible_os_family == "RedHat"
  
- name: Install xinetd | Ubuntu
  become: yes
  apt:
    name: xinetd
    state: present
  when: ansible_os_family == "Debian" and ansible_distribution_version == "14"
  
- name: Download inventory file check hardware:
  become: yes
  get_url:
    url: "{{ inventory_file }}"
    validate_certs: False
    dest: /usr/lib/check_mk_agent/plugins/
    mode: '0755'
  tags: inventory
  
- name: Enable filewall csf;
  become: yes
  shell: csf -a {{ check_mk_server_kt }} CheckMK
  tags: firewall
  
- name: Config CheckMK
  template:
    src: check_mk.j2
    dest: /etc/xinetd.d/check_mk
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
  tags: config
  notify: restart xinetd
